name: Classifier Landmarks test

on:
  schedule:
    - cron: '0 0 1 * *'

env:
  APP_NAME: recognize

jobs:
  classifier:
    runs-on: ubuntu-latest

    name: Test classifier landmarks

    strategy:
      fail-fast: false
      matrix:
        pure-js-mode: ['false']
        models:
          - landmarks_africa
          - landmarks_asia
          - landmarks_europe
          - landmarks_north_america
          - landmarks_south_america
          - landmarks_oceania

    steps:
      - name: Checkout app
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@06d6baf7d8f41934ab630e97d9e6c0bc9c9ac5e4 # v3
        id: versions
        with:
          fallbackNode: '^12'
          fallbackNpm: '^6'

      - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ steps.versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ steps.versions.outputs.npmVersion }}"

      - name: Install app
        run: |
          make all

      - name: Run classifier tests
        env:
          FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}
          RECOGNIZE_PUREJS: ${{ matrix.pure-js-mode }}
        run: |
          node tests/landmarks-tests.js ${{ matrix.models }}
